// Generated by CoffeeScript 1.6.2
window.xhGrab = function() {
  var data;

  data = {
    ids: []
  };
  $("#myform>table>tbody>tr").slice(1).each(function() {
    return data.ids.push($('td', this).eq(1).find('a').attr('href').match(/\d+/g)[0]);
  });
  return data;
};
