// Generated by CoffeeScript 1.6.2
window.xhGrab = function() {
  var data;

  data = {
    ids: []
  };
  $("article table td.title>a").each(function() {
    return data.ids.push(parseInt($(this).attr('href').match(/\d+/g)[0]));
  });
  return data;
};
