// Generated by CoffeeScript 1.6.2
window.xhGrab = function() {
  var data, pagenos;

  pagenos = $("div.page>a[pageno]");
  data = {
    count: parseInt(pagenos.eq(pagenos.length - 2).text())
  };
  return data;
};
