// Generated by CoffeeScript 1.6.2
window.spGrab = function() {
  var data;

  data = [];
  $('div.col1:first>.block').each(function() {
    var atcul, item, thumb, _this;

    _this = $(this);
    atcul = _this.children('.bar').children('ul');
    item = {
      ProviderId: _this.attr('id').match(/\d+/g)[0],
      ThumbUps: $.trim($('li', atcul).first().text()),
      ThumbDowns: $.trim($('li', atcul).eq(1).text())
    };
    thumb = $.trim(_this.children('.thumb').html());
    if (thumb) {
      item.Content = $.trim(_this.children('.content').html() + "<br />" + thumb);
    } else {
      item.Content = $.trim(_this.children('.content').html());
    }
    return data.push(item);
  });
  return data;
};
