// Generated by CoffeeScript 1.6.2
window.xhGrab = function() {
  var data;

  data = {
    ids: []
  };
  $('#center_list_id h2.toolong>a').each(function() {
    return data.ids.push(parseInt($(this).attr('href').match(/\d+/g)[0]));
  });
  return data;
};
