// Generated by CoffeeScript 1.6.2
exports.obj2asciiobj = function(data) {
  var key;

  for (key in data) {
    if (data.hasOwnProperty(key)) {
      data[key] = exports.str2ascii(data[key]);
    }
  }
  return data;
};

exports.str2ascii = function(str) {
  return str.replace(/[\u007f-\uffff]/g, function(c) {
    return "/u" + ('0000' + c.charCodeAt(0).toString(16)).slice(-4);
  });
};
