// Generated by CoffeeScript 1.6.2
var CastTesk, agentName, nta, serverUrl, system, websocket, _;

system = require("system");

if (system.args.length !== 3) {
  console.log('serverUrl and agentName is necessary!');
  phantom.exit(1);
}

agentName = system.args[1];

serverUrl = system.args[2];

_ = require('./underscore-min');

nta = require('./native2asic');

websocket = require("webpage").create();

websocket.settings.localToRemoteUrlAccessEnabled = true;

websocket.onConsoleMessage = function(info) {
  return console.log("~Websocket_Console: " + info);
};

websocket.onCallback = function(info) {
  switch (info.command) {
    case "CastTesk":
      return CastTesk(info.task);
  }
};

websocket.injectJs('./jquery.1.8.3.min.js');

websocket.injectJs('./jquery.signalR-1.1.1.min.js');

websocket.includeJs(serverUrl + '/signalr/hubs', function() {
  return websocket.evaluate(function(serverUrl, agentName) {
    var taskHub;

    $.support.cors = false;
    $.connection.hub.url = serverUrl + '/signalr';
    taskHub = $.connection.taskHub;
    $.connection.hub.start().done(function() {
      return taskHub.server.registerAgent(agentName);
    });
    return taskHub.client.castTesk = function(task) {
      var castTesk;

      castTesk = {
        command: "CastTesk",
        task: task
      };
      return window.callPhantom(castTesk);
    };
  }, serverUrl, agentName);
});

CastTesk = function(task) {
  var now, pageGrab;

  console.log("~CastTesk: " + JSON.stringify(task));
  pageGrab = require("webpage").create();
  pageGrab.settings.userAgent = 'Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.93 Safari/537.36';
  pageGrab.settings.loadImages = false;
  pageGrab.onError = function(msg, trace) {
    var msgStack;

    msgStack = [msg];
    if (trace) {
      trace.forEach(function(t) {
        var _ref;

        return msgStack.push(" -> " + t.file + ": " + t.line + ((_ref = t["function"]) != null ? _ref : " (in function '" + t["function"] + {
          "')": ""
        }));
      });
    }
    return console.log('~EvaluateError: ' + msgStack.join("\n"));
  };
  now = Date.now();
  return pageGrab.open(encodeURI(task.url), function(status) {
    var gbdate;

    gbdate = {};
    if (status !== 'success') {
      task.status = 'fail';
      task.error = 'Unable to access page';
    } else {
      pageGrab.injectJs('jquery.1.8.3.min.js');
      pageGrab.injectJs("grabscripts/" + task.site + "_" + task.command + ".js");
      gbdate = pageGrab.evaluate(function() {
        return spGrab();
      });
      task.spend = Date.now() - now;
      if (task.encoding === "gbk") {
        if (_.isArray(gbdate)) {
          _.each(gbdate, function(item, i) {
            return gbdate[i] = nta.obj2asciiobj(item);
          });
        } else {
          gbdate = nta.obj2asciiobj(gbdate);
        }
      }
    }
    pageGrab.close();
    task = JSON.stringify(task);
    gbdate = JSON.stringify(gbdate);
    console.log("~PostData: " + gbdate);
    return websocket.evaluate(function(task, data) {
      var taskHub;

      taskHub = $.connection.taskHub;
      return taskHub.server.postData(task, data);
    }, task, gbdate);
  });
};
